# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "b74b66d9bed456547af374c0563d5989"
name = "discount-announcement"
handle = "discount-announcement"
application_url = "https://force-parcel-coaching-possess.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "gen-test-store-individual.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_discounts,read_themes,write_products"

[auth]
redirect_urls = [
  "https://example.com/api/auth",
  "https://media-athletic-threaded-interventions.trycloudflare.com/auth/callback",
  "https://media-athletic-threaded-interventions.trycloudflare.com/auth/shopify/callback",
  "https://media-athletic-threaded-interventions.trycloudflare.com/api/auth/callback",
  "https://proposal-why-produce-kazakhstan.trycloudflare.com/auth/callback",
  "https://proposal-why-produce-kazakhstan.trycloudflare.com/auth/shopify/callback",
  "https://proposal-why-produce-kazakhstan.trycloudflare.com/api/auth/callback",
  "https://cambridge-league-folding-tennessee.trycloudflare.com/auth/callback",
  "https://cambridge-league-folding-tennessee.trycloudflare.com/auth/shopify/callback",
  "https://cambridge-league-folding-tennessee.trycloudflare.com/api/auth/callback",
  "https://finish-examined-destination-teddy.trycloudflare.com/auth/callback",
  "https://finish-examined-destination-teddy.trycloudflare.com/auth/shopify/callback",
  "https://finish-examined-destination-teddy.trycloudflare.com/api/auth/callback",
  "https://reveal-performances-phi-chan.trycloudflare.com/auth/callback",
  "https://reveal-performances-phi-chan.trycloudflare.com/auth/shopify/callback",
  "https://reveal-performances-phi-chan.trycloudflare.com/api/auth/callback",
  "https://trusted-bite-bosnia-claims.trycloudflare.com/auth/callback",
  "https://trusted-bite-bosnia-claims.trycloudflare.com/auth/shopify/callback",
  "https://trusted-bite-bosnia-claims.trycloudflare.com/api/auth/callback",
  "https://random-compile-runtime-carl.trycloudflare.com/auth/callback",
  "https://random-compile-runtime-carl.trycloudflare.com/auth/shopify/callback",
  "https://random-compile-runtime-carl.trycloudflare.com/api/auth/callback",
  "https://hansen-duke-chambers-hands.trycloudflare.com/auth/callback",
  "https://hansen-duke-chambers-hands.trycloudflare.com/auth/shopify/callback",
  "https://hansen-duke-chambers-hands.trycloudflare.com/api/auth/callback",
  "https://clients-fe-prototype-ipaq.trycloudflare.com/auth/callback",
  "https://clients-fe-prototype-ipaq.trycloudflare.com/auth/shopify/callback",
  "https://clients-fe-prototype-ipaq.trycloudflare.com/api/auth/callback",
  "https://heating-generate-andrews-realize.trycloudflare.com/auth/callback",
  "https://heating-generate-andrews-realize.trycloudflare.com/auth/shopify/callback",
  "https://heating-generate-andrews-realize.trycloudflare.com/api/auth/callback",
  "https://britain-government-shaped-column.trycloudflare.com/auth/callback",
  "https://britain-government-shaped-column.trycloudflare.com/auth/shopify/callback",
  "https://britain-government-shaped-column.trycloudflare.com/api/auth/callback",
  "https://optional-gray-v-mandate.trycloudflare.com/auth/callback",
  "https://optional-gray-v-mandate.trycloudflare.com/auth/shopify/callback",
  "https://optional-gray-v-mandate.trycloudflare.com/api/auth/callback",
  "https://offering-entities-penn-epic.trycloudflare.com/auth/callback",
  "https://offering-entities-penn-epic.trycloudflare.com/auth/shopify/callback",
  "https://offering-entities-penn-epic.trycloudflare.com/api/auth/callback",
  "https://essays-friend-zinc-boy.trycloudflare.com/auth/callback",
  "https://essays-friend-zinc-boy.trycloudflare.com/auth/shopify/callback",
  "https://essays-friend-zinc-boy.trycloudflare.com/api/auth/callback",
  "https://manhattan-recipients-holding-deaf.trycloudflare.com/auth/callback",
  "https://manhattan-recipients-holding-deaf.trycloudflare.com/auth/shopify/callback",
  "https://manhattan-recipients-holding-deaf.trycloudflare.com/api/auth/callback",
  "https://france-joint-choices-interference.trycloudflare.com/auth/callback",
  "https://france-joint-choices-interference.trycloudflare.com/auth/shopify/callback",
  "https://france-joint-choices-interference.trycloudflare.com/api/auth/callback",
  "https://oct-reservations-gba-provincial.trycloudflare.com/auth/callback",
  "https://oct-reservations-gba-provincial.trycloudflare.com/auth/shopify/callback",
  "https://oct-reservations-gba-provincial.trycloudflare.com/api/auth/callback",
  "https://omaha-designing-street-techrepublic.trycloudflare.com/auth/callback",
  "https://omaha-designing-street-techrepublic.trycloudflare.com/auth/shopify/callback",
  "https://omaha-designing-street-techrepublic.trycloudflare.com/api/auth/callback",
  "https://said-inside-stories-driven.trycloudflare.com/auth/callback",
  "https://said-inside-stories-driven.trycloudflare.com/auth/shopify/callback",
  "https://said-inside-stories-driven.trycloudflare.com/api/auth/callback",
  "https://expanding-furniture-warm-mysimon.trycloudflare.com/auth/callback",
  "https://expanding-furniture-warm-mysimon.trycloudflare.com/auth/shopify/callback",
  "https://expanding-furniture-warm-mysimon.trycloudflare.com/api/auth/callback",
  "https://worm-qualify-fighting-boulevard.trycloudflare.com/auth/callback",
  "https://worm-qualify-fighting-boulevard.trycloudflare.com/auth/shopify/callback",
  "https://worm-qualify-fighting-boulevard.trycloudflare.com/api/auth/callback",
  "https://examines-analyzed-husband-toxic.trycloudflare.com/auth/callback",
  "https://examines-analyzed-husband-toxic.trycloudflare.com/auth/shopify/callback",
  "https://examines-analyzed-husband-toxic.trycloudflare.com/api/auth/callback",
  "https://investors-brake-virus-securities.trycloudflare.com/auth/callback",
  "https://investors-brake-virus-securities.trycloudflare.com/auth/shopify/callback",
  "https://investors-brake-virus-securities.trycloudflare.com/api/auth/callback",
  "https://indices-acrylic-citations-occasions.trycloudflare.com/auth/callback",
  "https://indices-acrylic-citations-occasions.trycloudflare.com/auth/shopify/callback",
  "https://indices-acrylic-citations-occasions.trycloudflare.com/api/auth/callback",
  "https://licensed-daughter-island-television.trycloudflare.com/auth/callback",
  "https://licensed-daughter-island-television.trycloudflare.com/auth/shopify/callback",
  "https://licensed-daughter-island-television.trycloudflare.com/api/auth/callback",
  "https://force-parcel-coaching-possess.trycloudflare.com/auth/callback",
  "https://force-parcel-coaching-possess.trycloudflare.com/auth/shopify/callback",
  "https://force-parcel-coaching-possess.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-10"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

[pos]
embedded = false
