# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "b74b66d9bed456547af374c0563d5989"
name = "discount-announcement"
handle = "discount-announcement"
application_url = "https://britain-government-shaped-column.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "gen-test-store-individual.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_discounts,write_products"

[auth]
redirect_urls = [
  "https://example.com/api/auth",
  "https://media-athletic-threaded-interventions.trycloudflare.com/auth/callback",
  "https://media-athletic-threaded-interventions.trycloudflare.com/auth/shopify/callback",
  "https://media-athletic-threaded-interventions.trycloudflare.com/api/auth/callback",
  "https://proposal-why-produce-kazakhstan.trycloudflare.com/auth/callback",
  "https://proposal-why-produce-kazakhstan.trycloudflare.com/auth/shopify/callback",
  "https://proposal-why-produce-kazakhstan.trycloudflare.com/api/auth/callback",
  "https://cambridge-league-folding-tennessee.trycloudflare.com/auth/callback",
  "https://cambridge-league-folding-tennessee.trycloudflare.com/auth/shopify/callback",
  "https://cambridge-league-folding-tennessee.trycloudflare.com/api/auth/callback",
  "https://finish-examined-destination-teddy.trycloudflare.com/auth/callback",
  "https://finish-examined-destination-teddy.trycloudflare.com/auth/shopify/callback",
  "https://finish-examined-destination-teddy.trycloudflare.com/api/auth/callback",
  "https://reveal-performances-phi-chan.trycloudflare.com/auth/callback",
  "https://reveal-performances-phi-chan.trycloudflare.com/auth/shopify/callback",
  "https://reveal-performances-phi-chan.trycloudflare.com/api/auth/callback",
  "https://trusted-bite-bosnia-claims.trycloudflare.com/auth/callback",
  "https://trusted-bite-bosnia-claims.trycloudflare.com/auth/shopify/callback",
  "https://trusted-bite-bosnia-claims.trycloudflare.com/api/auth/callback",
  "https://random-compile-runtime-carl.trycloudflare.com/auth/callback",
  "https://random-compile-runtime-carl.trycloudflare.com/auth/shopify/callback",
  "https://random-compile-runtime-carl.trycloudflare.com/api/auth/callback",
  "https://hansen-duke-chambers-hands.trycloudflare.com/auth/callback",
  "https://hansen-duke-chambers-hands.trycloudflare.com/auth/shopify/callback",
  "https://hansen-duke-chambers-hands.trycloudflare.com/api/auth/callback",
  "https://clients-fe-prototype-ipaq.trycloudflare.com/auth/callback",
  "https://clients-fe-prototype-ipaq.trycloudflare.com/auth/shopify/callback",
  "https://clients-fe-prototype-ipaq.trycloudflare.com/api/auth/callback",
  "https://heating-generate-andrews-realize.trycloudflare.com/auth/callback",
  "https://heating-generate-andrews-realize.trycloudflare.com/auth/shopify/callback",
  "https://heating-generate-andrews-realize.trycloudflare.com/api/auth/callback",
  "https://britain-government-shaped-column.trycloudflare.com/auth/callback",
  "https://britain-government-shaped-column.trycloudflare.com/auth/shopify/callback",
  "https://britain-government-shaped-column.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-10"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

[pos]
embedded = false
